### PR TITLE
Hsqldb

### PR DESCRIPTION
**Pull request by sevagh**
* Add HSQLDB in memory for real Dao unit tests (configured in persistence.xml)
* Update lastPostedBy in updateLinks(), and add a unit test for it reposting a link
* Renamed count to count_ in Link object to avoid HSQL clash (I wish I could find a better solution)
* Changed up test-context.xml to not create beans we don't use in testing yet

### CODE REVIEW

**Comment by sevagh** [comment]
I noticed I had made some mistakes in my last pull request, and some of the unit tests I added weren't even testing the logic properly properly.

Anyway you fixed most of them in your last commit and the unit tests should be better now.

**Comment by sevagh** [comment]
Want me to resubmit without that commit?

**Comment by benco03** [comment]
Nah its fine. I'll be ripping the whole thing apart when i start to play
with modularisation. As far as I'm aware when a variable is autowired it
only uses the one instance of the dao so there shouldn't be any problems
with that.

**Comment by sevagh** [comment]
Ah... didn't know that.

**Pull request merged**
